---
title: "My first markdown"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, error=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)
library(forcats)

```

## Reading the Data

The data represents a list of students' favorite resturants and their characteristics.

```{r, message=FALSE, error=FALSE, echo=FALSE}
fav_restaurants <- read_csv("https://raw.githubusercontent.com/URstats/stat209-s18-andreacelleri/master/fav_restaurants.csv")

```
## Plotting the Data

Plot shows the relationship between yearly visits and cost per person of the restaurant. 

``` {r, message=FALSE, echo=FALSE}
ggplot(fav_restaurants, aes(yearly_visits,cost_per_person,)) +
  theme_bw() +
  geom_point() +
  labs(y="Cost per Person", x="Times Visited per Year", Title= "Relationship between Cost and Times Visited")

```
### Plotting Data

Shows the location of the students' favorite restaurants by location. 

``` {r}
ggplot(fav_restaurants, aes(location)) +
  theme_bw() +
  geom_bar()

``` 
### Plotting Data

``` {r}
ggplot(fav_restaurants, aes(cuisine))+
  theme_bw() +
  geom_bar()

```

